version: "3.9"

services:
  app:
    build: .
    container_name: flash-sale-engine-test
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

  db:
    image: postgres:16
    container_name: flashsale-db
    environment:
      POSTGRES_USER: tekkomta
      POSTGRES_PASSWORD: Tekkomta2023
      POSTGRES_DB: flashsale
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: flashsale-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
